<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Console interface for ZLR.</Description>
    <Authors>Jesse McGrew</Authors>
    <Copyright>Copyright © 2007-2018 Jesse McGrew</Copyright>
    <RepositoryUrl>https://bitbucket.org/jmcgrew/zlr</RepositoryUrl>
    <PackageProjectUrl>https://bitbucket.org/jmcgrew/zlr/overview</PackageProjectUrl>
    <PackageIconUrl>https://bytebucket.org/jmcgrew/zlr/raw/tip/zlr-logo.png</PackageIconUrl>
    <RepositoryType>mercurial</RepositoryType>
    <AssemblyVersion>0.9.0.0</AssemblyVersion>
    
    <TargetFramework>net471</TargetFramework>
    <Prefer32Bit>false</Prefer32Bit>
    <OutputType>Exe</OutputType>

    <RootNamespace>ZLR.Interfaces.SystemConsole</RootNamespace>
    <LangVersion>7.2</LangVersion>

    <CodeAnalysisRuleSet>..\ZLR.ruleset</CodeAnalysisRuleSet>

    <PublishUrl>publish\</PublishUrl>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZLR.VM\ZLR.VM.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2018.3.0">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Nito.AsyncEx" Version="5.0.0-pre-05" />
    <PackageReference Include="System.Collections.Immutable" Version="1.5.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime" Version="4.6.6" />
    <PackageReference Include="Antlr4.CodeGenerator" Version="4.6.6">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>