<!--EXTERNAL_PROPERTIES: TargetFramework-->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>0.9.0-pre-01</Version>
    <Authors>Jesse McGrew</Authors>
    <Company />
    <Product>ZLR</Product>
    <PackageProjectUrl>https://bitbucket.org/jmcgrew/zlr</PackageProjectUrl>
    <RepositoryUrl>https://bitbucket.org/jmcgrew/zlr</RepositoryUrl>
    <RepositoryType>mercurial</RepositoryType>
    <PackageLicenseExpression>LGPL-2.1-only</PackageLicenseExpression>
    <Copyright>Copyright 2007-2018 Jesse McGrew</Copyright>
    <PackageTags>zlr z-machine zmachine z-code zcode infocom jit interpreter</PackageTags>
    <PackageIconUrl>http://zlr.sourceforge.net/zlr-icon-32x32.png</PackageIconUrl>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Description>A Z-Machine interpreter.</Description>
    <CodeAnalysisRuleSet>..\ZLR.ruleset</CodeAnalysisRuleSet>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\ZLR.VM.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2020.1.0">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Nito.AsyncEx" Version="5.0.0" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
    <DefineConstants>HAVE_SPAN</DefineConstants>
  </PropertyGroup>

</Project>